/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#adc7fc",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#444653",
        "tertiary": "#611e00",
        "primary-fixed": "#dde1ff",
        "on-tertiary-fixed-variant": "#802a00",
        "tertiary-container": "#872d00",
        "on-error-container": "#93000a",
        "surface-bright": "#faf8ff",
        "on-primary-fixed-variant": "#173bab",
        "on-primary": "#ffffff",
        "on-primary-container": "#a8b8ff",
        "secondary-fixed": "#d7e2ff",
        "on-error": "#ffffff",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "on-secondary-fixed-variant": "#2c4674",
        "tertiary-fixed": "#ffdbce",
        "surface": "#faf8ff",
        "tertiary-fixed-dim": "#ffb59a",
        "primary-fixed-dim": "#b8c4ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "secondary": "#455e8d",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "primary-container": "#1e40af",
        "on-secondary-fixed": "#001b3f",
        "on-primary-fixed": "#001453",
        "on-background": "#131b2e",
        "inverse-primary": "#b8c4ff",
        "on-tertiary-container": "#ffa583",
        "on-secondary-container": "#3b5482",
        "inverse-on-surface": "#eef0ff",
        "outline-variant": "#c4c5d5",
        "background": "#faf8ff",
        "on-tertiary-fixed": "#380d00",
        "surface-container": "#eaedff",
        "on-tertiary": "#ffffff",
        "outline": "#757684",
        "surface-container-low": "#f2f3ff",
        "surface-container-highest": "#dae2fd",
        "surface-tint": "#3755c3",
        "primary": "#00288e",
        "secondary-container": "#b0caff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-md": "1.5rem",
        "space-md": "0.75rem",
        "space-2xl": "2rem",
        "space-sm": "0.5rem",
        "space-xl": "1.5rem",
        "gutter": "1rem",
        "space-lg": "1rem",
        "margin-lg": "2rem",
        "gutter-lg": "1.5rem",
        "space-xs": "0.25rem",
        "margin": "1rem",
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "code-xs": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.025em", fontWeight: "600" }],
        "label-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "headline-sm": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "code-sm": ["0.75rem", { lineHeight: "1.125rem", fontWeight: "400" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "code-xs": ["0.6875rem", { lineHeight: "1rem", fontWeight: "400" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
